*.class

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.ear

#Gradle temporary files
target/

#Eclipse files
**/.project
**/.classpath
**/.settings/
blog/bin/
**/.tern-project

#IntelliJ files
**/*.iml
**/.idea
**/.gradle

**/.sts4-cache/


.DS_STORE
node_modules
scripts/flow/*/.flowconfig
*~
*.pyc
.grunt
_SpecRunner.html
__benchmarks__
build/
coverage/
flow-coverage/
.module-cache
fixtures/dom/public/react-dom.js
fixtures/dom/public/react.js
test/the-files-to-test.generated.js
*.log*
chrome-user-data
*.sublime-project
*.sublime-workspace
.idea
*.iml
.vscode
*.swp
*.swo
*.DS_Store